columnSuffix: null
contentColumnType: text
fieldGroup: 8d3cabd4-1037-4e8e-8417-8b6361290ec6 # Common
handle: productDescription
instructions: null
name: 'Product Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
