dateModified: 1637927797
email:
  fromEmail: engineering@fostercommerce.com
  fromName: 'Snipcart Dev'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8d3cabd4-1037-4e8e-8417-8b6361290ec6: Common # Common
    83ea9cdc-c4be-4c53-b40f-1d1e75f9ff73: 'Product Details' # Product Details
    ce2b6eb1-d61e-44e6-bd0b-dce122ce1433: 'Public Schema' # Public Schema
    e8ef8494-36a9-4ecc-b0b8-33bdc34343ae: 'Dev Schema' # Dev Schema
plugins:
  snipcart:
    edition: standard
    enabled: true
    licenseKey: MQ3MAC5BAFX41SCC90KZ4POD
    schemaVersion: 1.0.10
    settings:
      cacheDurationLimit: '300'
      cacheResponses: ''
      customerNotificationEmailTemplate: ''
      defaultCurrency: usd
      enabledCurrencies:
        - usd
      logCustomRates: '1'
      logWebhookRequests: '1'
      notificationEmailTemplate: ''
      notificationEmails: ''
      orderCommentsFieldName: ''
      orderGiftNoteFieldName: ''
      providerSettings:
        __assoc__:
          -
            - shipStation
            -
              __assoc__:
                -
                  - apiKey
                  - ''
                -
                  - apiSecret
                  - ''
                -
                  - defaultCarrierCode
                  - ''
                -
                  - defaultPackageCode
                  - ''
                -
                  - defaultCountry
                  - ''
                -
                  - defaultOrderConfirmation
                  - none
                -
                  - defaultWarehouseId
                  - ''
                -
                  - enableShippingRates
                  - ''
                -
                  - sendCompletedOrders
                  - ''
      publicApiKey: $SNIPCART_PUBLIC_API_KEY
      publicTestApiKey: $SNIPCART_PUBLIC_API_KEY
      reFeedAttemptWindow: 15
      reduceQuantitiesOnOrder: '1'
      secretApiKey: $SNIPCART_SECRET_API_KEY
      secretTestApiKey: $SNIPCART_SECRET_API_KEY
      sendCustomerOrderNotificationEmail: ''
      sendOrderNotificationEmail: ''
      sendTestModeEmail: ''
      shipFromAddress:
        __assoc__:
          -
            - name
            - ''
          -
            - companyName
            - ''
          -
            - address1
            - ''
          -
            - address2
            - ''
          -
            - city
            - ''
          -
            - province
            - ''
          -
            - postalCode
            - ''
          -
            - country
            - ''
          -
            - phone
            - ''
          -
            - email
            - ''
      testMode: '1'
system:
  edition: pro
  live: true
  name: 'Snipcart Dev'
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
