dateModified: 1694170433
email:
  fromEmail: engineering@fostercommerce.com
  fromName: 'Snipcart Dev'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2eb8dccb-b22e-43c9-be2d-d3f76a3856c1: 'Product Description' # Product Description
    8d3cabd4-1037-4e8e-8417-8b6361290ec6: Common # Common
    83ea9cdc-c4be-4c53-b40f-1d1e75f9ff73: 'Product Details' # Product Details
    6884bf14-6cfc-4f23-ac2f-3702687f8602: Heading # Heading
    97134205-e4b8-4169-a51b-ca23329ec35a: 'Product Info' # Product Info
    a4e5c444-dfe0-4cc9-81d2-385dca72e446: Heading # Heading
    c7fd47c1-7147-466b-9710-16b4d5d9c0e2: 'Product Name' # Product Name
    ce2b6eb1-d61e-44e6-bd0b-dce122ce1433: 'Public Schema' # Public Schema
    db133a46-b847-4150-a31b-741c83c342a5: Product # Product
    e8ef8494-36a9-4ecc-b0b8-33bdc34343ae: 'Dev Schema' # Dev Schema
    eff3417c-3955-4de7-a137-b7a99e365c5c: 'Product Options' # Product Options
    f7f5703c-a5d1-4ece-81f6-cd69aacba8cb: 'Page Blocks' # Page Blocks
plugins:
  snipcart:
    edition: standard
    enabled: true
    licenseKey: MQ3MAC5BAFX41SCC90KZ4POD
    schemaVersion: 1.0.10
    settings:
      cacheDurationLimit: '300'
      cacheResponses: ''
      customerNotificationEmailTemplate: ''
      defaultCurrency: usd
      enabledCurrencies:
        - usd
      logCustomRates: '1'
      logWebhookRequests: '1'
      notificationEmailTemplate: ''
      notificationEmails: ''
      orderCommentsFieldName: ''
      orderGiftNoteFieldName: ''
      providerSettings:
        __assoc__:
          -
            - shipStation
            -
              __assoc__:
                -
                  - apiKey
                  - ''
                -
                  - apiSecret
                  - ''
                -
                  - defaultCarrierCode
                  - ''
                -
                  - defaultPackageCode
                  - ''
                -
                  - defaultCountry
                  - ''
                -
                  - defaultOrderConfirmation
                  - none
                -
                  - defaultWarehouseId
                  - ''
                -
                  - enableShippingRates
                  - ''
                -
                  - sendCompletedOrders
                  - ''
      publicApiKey: $SNIPCART_PUBLIC_API_KEY
      publicTestApiKey: $SNIPCART_PUBLIC_API_KEY
      reFeedAttemptWindow: 15
      reduceQuantitiesOnOrder: '1'
      secretApiKey: $SNIPCART_SECRET_API_KEY
      secretTestApiKey: $SNIPCART_SECRET_API_KEY
      sendCustomerOrderNotificationEmail: ''
      sendOrderNotificationEmail: ''
      sendTestModeEmail: ''
      shipFromAddress:
        __assoc__:
          -
            - name
            - ''
          -
            - companyName
            - ''
          -
            - address1
            - ''
          -
            - address2
            - ''
          -
            - city
            - ''
          -
            - province
            - ''
          -
            - postalCode
            - ''
          -
            - country
            - ''
          -
            - phone
            - ''
          -
            - email
            - ''
      testMode: '1'
system:
  edition: pro
  live: true
  name: 'Snipcart Dev'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
